// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace CombineIndividualDistances_dMUncorrelated_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 17> locations_array__ =
  {" (found before start of program)",
  " (in '/Users/samward/Documents/PhD/sigmaRel_computer/sigmaRel_computer/model_files/stan_files/CombineIndividualDistances_dMUncorrelated.stan', line 11, column 2 to column 25)",
  " (in '/Users/samward/Documents/PhD/sigmaRel_computer/sigmaRel_computer/model_files/stan_files/CombineIndividualDistances_dMUncorrelated.stan', line 12, column 2 to column 10)",
  " (in '/Users/samward/Documents/PhD/sigmaRel_computer/sigmaRel_computer/model_files/stan_files/CombineIndividualDistances_dMUncorrelated.stan', line 16, column 2 to column 21)",
  " (in '/Users/samward/Documents/PhD/sigmaRel_computer/sigmaRel_computer/model_files/stan_files/CombineIndividualDistances_dMUncorrelated.stan', line 18, column 2 to column 39)",
  " (in '/Users/samward/Documents/PhD/sigmaRel_computer/sigmaRel_computer/model_files/stan_files/CombineIndividualDistances_dMUncorrelated.stan', line 23, column 2 to column 31)",
  " (in '/Users/samward/Documents/PhD/sigmaRel_computer/sigmaRel_computer/model_files/stan_files/CombineIndividualDistances_dMUncorrelated.stan', line 24, column 2 to column 38)",
  " (in '/Users/samward/Documents/PhD/sigmaRel_computer/sigmaRel_computer/model_files/stan_files/CombineIndividualDistances_dMUncorrelated.stan', line 26, column 2 to column 48)",
  " (in '/Users/samward/Documents/PhD/sigmaRel_computer/sigmaRel_computer/model_files/stan_files/CombineIndividualDistances_dMUncorrelated.stan', line 2, column 2 to column 17)",
  " (in '/Users/samward/Documents/PhD/sigmaRel_computer/sigmaRel_computer/model_files/stan_files/CombineIndividualDistances_dMUncorrelated.stan', line 3, column 9 to column 10)",
  " (in '/Users/samward/Documents/PhD/sigmaRel_computer/sigmaRel_computer/model_files/stan_files/CombineIndividualDistances_dMUncorrelated.stan', line 3, column 2 to column 17)",
  " (in '/Users/samward/Documents/PhD/sigmaRel_computer/sigmaRel_computer/model_files/stan_files/CombineIndividualDistances_dMUncorrelated.stan', line 4, column 9 to column 10)",
  " (in '/Users/samward/Documents/PhD/sigmaRel_computer/sigmaRel_computer/model_files/stan_files/CombineIndividualDistances_dMUncorrelated.stan', line 4, column 2 to column 21)",
  " (in '/Users/samward/Documents/PhD/sigmaRel_computer/sigmaRel_computer/model_files/stan_files/CombineIndividualDistances_dMUncorrelated.stan', line 6, column 2 to column 15)",
  " (in '/Users/samward/Documents/PhD/sigmaRel_computer/sigmaRel_computer/model_files/stan_files/CombineIndividualDistances_dMUncorrelated.stan', line 7, column 2 to column 23)",
  " (in '/Users/samward/Documents/PhD/sigmaRel_computer/sigmaRel_computer/model_files/stan_files/CombineIndividualDistances_dMUncorrelated.stan', line 11, column 9 to column 10)",
  " (in '/Users/samward/Documents/PhD/sigmaRel_computer/sigmaRel_computer/model_files/stan_files/CombineIndividualDistances_dMUncorrelated.stan', line 16, column 9 to column 10)"};
class CombineIndividualDistances_dMUncorrelated_model final : public 
 model_base_crtp<CombineIndividualDistances_dMUncorrelated_model> {
 private:
  int S;
  Eigen::Matrix<double,-1,1> mu_s_data__;
  Eigen::Matrix<double,-1,1> mu_err_s_data__;
  double mean_mu;
  double sigma0;
  Eigen::Map<Eigen::Matrix<double,-1,1>> mu_s{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> mu_err_s{nullptr, 0};
 public:
  ~CombineIndividualDistances_dMUncorrelated_model() {}
  CombineIndividualDistances_dMUncorrelated_model(stan::io::var_context&
                                                  context__, unsigned int
                                                  random_seed__ = 0,
                                                  std::ostream*
                                                  pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "CombineIndividualDistances_dMUncorrelated_model_namespace::CombineIndividualDistances_dMUncorrelated_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 8;
      context__.validate_dims("data initialization", "S", "int",
        std::vector<size_t>{});
      S = std::numeric_limits<int>::min();
      current_statement__ = 8;
      S = context__.vals_i("S")[(1 - 1)];
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "S", S, 1);
      current_statement__ = 9;
      stan::math::validate_non_negative_index("mu_s", "S", S);
      current_statement__ = 10;
      context__.validate_dims("data initialization", "mu_s", "double",
        std::vector<size_t>{static_cast<size_t>(S)});
      mu_s_data__ = Eigen::Matrix<double,-1,1>::Constant(S,
                      std::numeric_limits<double>::quiet_NaN());
      new (&mu_s) Eigen::Map<Eigen::Matrix<double,-1,1>>(mu_s_data__.data(),
        S);
      {
        std::vector<local_scalar_t__> mu_s_flat__;
        current_statement__ = 10;
        mu_s_flat__ = context__.vals_r("mu_s");
        current_statement__ = 10;
        pos__ = 1;
        current_statement__ = 10;
        for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
          current_statement__ = 10;
          stan::model::assign(mu_s, mu_s_flat__[(pos__ - 1)],
            "assigning variable mu_s", stan::model::index_uni(sym1__));
          current_statement__ = 10;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 11;
      stan::math::validate_non_negative_index("mu_err_s", "S", S);
      current_statement__ = 12;
      context__.validate_dims("data initialization", "mu_err_s", "double",
        std::vector<size_t>{static_cast<size_t>(S)});
      mu_err_s_data__ = Eigen::Matrix<double,-1,1>::Constant(S,
                          std::numeric_limits<double>::quiet_NaN());
      new (&mu_err_s)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(mu_err_s_data__.data(), S);
      {
        std::vector<local_scalar_t__> mu_err_s_flat__;
        current_statement__ = 12;
        mu_err_s_flat__ = context__.vals_r("mu_err_s");
        current_statement__ = 12;
        pos__ = 1;
        current_statement__ = 12;
        for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
          current_statement__ = 12;
          stan::model::assign(mu_err_s, mu_err_s_flat__[(pos__ - 1)],
            "assigning variable mu_err_s", stan::model::index_uni(sym1__));
          current_statement__ = 12;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 13;
      context__.validate_dims("data initialization", "mean_mu", "double",
        std::vector<size_t>{});
      mean_mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 13;
      mean_mu = context__.vals_r("mean_mu")[(1 - 1)];
      current_statement__ = 14;
      context__.validate_dims("data initialization", "sigma0", "double",
        std::vector<size_t>{});
      sigma0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 14;
      sigma0 = context__.vals_r("sigma0")[(1 - 1)];
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "sigma0", sigma0, 0);
      current_statement__ = 15;
      stan::math::validate_non_negative_index("eta_dM_Rel_s", "S", S);
      current_statement__ = 16;
      stan::math::validate_non_negative_index("dM_Rel_s", "S", S);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = S + 1;
  }
  inline std::string model_name() const final {
    return "CombineIndividualDistances_dMUncorrelated_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = "};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "CombineIndividualDistances_dMUncorrelated_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> eta_dM_Rel_s =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
      current_statement__ = 1;
      eta_dM_Rel_s = in__.template read<
                       Eigen::Matrix<local_scalar_t__,-1,1>>(S);
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 2;
      mu = in__.template read<local_scalar_t__>();
      Eigen::Matrix<local_scalar_t__,-1,1> dM_Rel_s =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(dM_Rel_s,
        stan::math::multiply(sigma0, eta_dM_Rel_s),
        "assigning variable dM_Rel_s");
      {
        current_statement__ = 5;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(eta_dM_Rel_s));
        current_statement__ = 6;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu, mean_mu, 100));
        current_statement__ = 7;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu_s,
                         stan::math::add(mu, dM_Rel_s), mu_err_s));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "CombineIndividualDistances_dMUncorrelated_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> eta_dM_Rel_s =
        Eigen::Matrix<double,-1,1>::Constant(S,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      eta_dM_Rel_s = in__.template read<
                       Eigen::Matrix<local_scalar_t__,-1,1>>(S);
      double mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      mu = in__.template read<local_scalar_t__>();
      Eigen::Matrix<double,-1,1> dM_Rel_s =
        Eigen::Matrix<double,-1,1>::Constant(S,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(eta_dM_Rel_s);
      out__.write(mu);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 4;
      stan::model::assign(dM_Rel_s,
        stan::math::multiply(sigma0, eta_dM_Rel_s),
        "assigning variable dM_Rel_s");
      if (emit_transformed_parameters__) {
        out__.write(dM_Rel_s);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> eta_dM_Rel_s =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(eta_dM_Rel_s,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(S),
        "assigning variable eta_dM_Rel_s");
      out__.write(eta_dM_Rel_s);
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 2;
      mu = in__.read<local_scalar_t__>();
      out__.write(mu);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "eta_dM_Rel_s",
        "double", std::vector<size_t>{static_cast<size_t>(S)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "mu", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> eta_dM_Rel_s =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> eta_dM_Rel_s_flat__;
        current_statement__ = 1;
        eta_dM_Rel_s_flat__ = context__.vals_r("eta_dM_Rel_s");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(eta_dM_Rel_s, eta_dM_Rel_s_flat__[(pos__ - 1)],
            "assigning variable eta_dM_Rel_s", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(eta_dM_Rel_s);
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 2;
      mu = context__.vals_r("mu")[(1 - 1)];
      out__.write(mu);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"eta_dM_Rel_s", "mu"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"dM_Rel_s"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(S)},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(S)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
      param_names__.emplace_back(std::string() + "eta_dM_Rel_s" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "mu");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
        param_names__.emplace_back(std::string() + "dM_Rel_s" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
      param_names__.emplace_back(std::string() + "eta_dM_Rel_s" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "mu");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
        param_names__.emplace_back(std::string() + "dM_Rel_s" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"eta_dM_Rel_s\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(S) + "},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"dM_Rel_s\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(S) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"eta_dM_Rel_s\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(S) + "},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"dM_Rel_s\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(S) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (S + 1);
    const size_t num_transformed = emit_transformed_parameters * (S);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (S + 1);
    const size_t num_transformed = emit_transformed_parameters * (S);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = CombineIndividualDistances_dMUncorrelated_model_namespace::CombineIndividualDistances_dMUncorrelated_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return CombineIndividualDistances_dMUncorrelated_model_namespace::profiles__;
}
#endif